### ISSUE TITLE
Optimise hybi/stream_reader.js

### ISSUE THREAD

**Issue by zingaburga** [faye/websocket-driver-node#10]
I don't have a lot to say about this, but I've rewritten the StreamReader.read function from lib/websocket/driver/hybi/stream_reader.js to try an improve its efficiency.

http://pastebin.com/yZE38kf1

I don't have any benchmark figures, but it seems to reduce CPU usage in my application.  A key idea is to reduce the amount of manual copying and work done in Javascript.
I'm also unsure of what compatibility is like with older versions of Node (if this is desired) although I suspect it should work on all 0.10.x and later (Buffer.slice and Buffer.concat need to be available).

I just thought I'd post this in case anyone found this useful / willing to perform extra tests etc.
Thanks for all the work done on this module!

**Comment by glasser** [comment]
My impression is that `Buffer.slice` is an O(1) operation and I can see why this would lead to a speedup over the current code (and since slice is fast, no reason to keep around the extra `_cursor` state), but do you actually see speedup from using `concat`?  `concat` is just implemented as a JS loop calling copy...

**Comment by zingaburga** [comment]
Probably not, I haven't done extensive testing.
The idea was to push as much functionality to node interfaces which may or may not eventually change (e.g. if they come up with a smarter implementation of concat).

Thanks for the response.

**Comment by jcoglan** [comment]
@zingaburga Could you submit this as a pull request?

**Comment by jcoglan** [comment]
Never mind, I need to get a release done so I've imported it myself in 8cf42d6.
