### ISSUE TITLE
If an extension's processOutgoingMessage is asynchronous, order of message and close may be reversed

### ISSUE THREAD

**Issue by glasser** [faye/websocket-driver-node#11]
This is the issue I was describing at https://github.com/faye/permessage-deflate-node/pull/3

I am going to try to write a test or example program to demonstrate this in something smaller than the Meteor codebase, but it's definitely the case that if you write an extension whose processOutgoingMessage doesn't call its callback synchronously, and you try to write a text message to the socket and then immediately close the websocket, Faye can write the close message before writing the text message.

**Comment by glasser** [comment]
OK, here's one reproduction.

```
glasser@perseid 0 /tmp/issue-11 $ git clone -b driver-issue-11 https://github.com/glasser/faye-websocket-node >/dev/null
glasser@perseid 0 /tmp/issue-11 $ git clone -b driver-issue-11 https://github.com/glasser/websocket-driver-node >/dev/null
glasser@perseid 130 /tmp/issue-11/websocket-driver-node driver-issue-11 u= $ cd faye-websocket-node/
glasser@perseid 0 /tmp/issue-11/faye-websocket-node driver-issue-11 u= $ npm install >/dev/null
glasser@perseid 0 /tmp/issue-11/faye-websocket-node driver-issue-11 u= $ cd ../websocket-driver-node/
glasser@perseid 0 /tmp/issue-11/websocket-driver-node driver-issue-11 u= $ npm install >/dev/null
glasser@perseid 130 /tmp/issue-11/websocket-driver-node driver-issue-11 u= $ (cd ../faye-websocket-node/ && sleep 1 && node examples/client.js http://localhost:12345/) & node examples/tcp_server.js 12345
[1] 72293
SENDING FRAME 1
SENDING FRAME 8
[open] { upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-accept': 'L8A3rmV2Xv3Hu5u/oSlaSYuXlgo=',
  'sec-websocket-extensions': 'permessage-delay' }
[message] Hello from a server
[close] 1000 
  C-c C-c[1]+  Done                    ( cd ../faye-websocket-node/ && sleep 1 && node examples/client.js http://localhost:12345/ )
```

Note the order of the two sent frames: 1 (text) then 8 (close).

Hit CTRL-C to kill the server. Then:

```
glasser@perseid 130 /tmp/issue-11/websocket-driver-node driver-issue-11 u= $ (cd ../faye-websocket-node/ && sleep 1 && node examples/client.js http://localhost:12345/) & MAKE_BUG=t node examples/tcp_server.js 12345
[1] 72321
SENDING FRAME 8
SENDING FRAME 1
[open] { upgrade: 'websocket',
  connection: 'Upgrade',
  'sec-websocket-accept': 'Qg5BF7DI7H4Lot+ZjNUjTGmndNo=',
  'sec-websocket-extensions': 'permessage-delay' }
[close] 1000 
  C-c C-c[1]+  Done                    ( cd ../faye-websocket-node/ && sleep 1 && node examples/client.js http://localhost:12345/ )
```

Note this time that the CLOSE is sent before the TEXT!

**Comment by glasser** [comment]
There is almost certainly an analogous bug in the opposite direction, where async processIncomingMessage calls can lead to the close event getting emitted before a message event that preceded it, BTW.

Probably the right answer is just to push ALL messages through the ExtensionSet pipelines, diverting non-message messages before they actually reach the Extension APIs.

**Comment by glasser** [comment]
Just to be clear — this is a pretty major bug, and it might make sense to roll back extension support (or at least place a warning in the README) until time is found to fix it.

**Comment by jcoglan** [comment]
I've commited https://github.com/faye/websocket-extensions-node/commit/1b77290e8279f654089eac963942309fb19b9312 and https://github.com/faye/websocket-driver-node/commit/cc5e5c245e6fd4c45f0c4f1821de5ff67b3018e7 to hopefully address this issue.

**Comment by glasser** [comment]
Thanks, this looks right.  One note: this change now means that the ordering of frames emitted by `driver.text(); driver.close()` is now guaranteed to be "text then close".  However, if I understand correctly, the driver does *not* guarantee that the ordering of frames emitted by `driver.text(); driver.ping()` is "text then ping", since ping does not go through the pipeline.

I think this is a reasonable choice, but worth documenting somewhere.

**Comment by jcoglan** [comment]
I'm not going to address the `ping` question at this time, since I don't have a lot of info on frame-level extensions. I'm addressing `close` because it affects the sending of messages, but `ping` does not. `ping` is an internal control mechanism and not an application-level concern, and without much to refer to on how frames vs messages ought to be dealt with by the extension pipeline, I'm leaving this undefined for now. It's fine as far as the spec goes for ping/pong to be interleaved with message frames.

Can I close this issue?

**Comment by glasser** [comment]
I mean, I was merely suggesting that you explicitly document (even just as an internal comment on the ping method in hybi.js) that the ordering is undefined. Otherwise it's somewhat subtle to notice that it's the one kind of message that doesn't interact with the extensions pipeline.

Haven't yet tested the code (just read it) but it sure looks like this should be fixed, yup.
