### ISSUE TITLE
Consider more robust method of HTTP parsing (and incidentally support io.js?)

### ISSUE THREAD

**Issue by robertdimarco** [faye/websocket-driver-node#12]
While checking out Faye's support for io.js, I ran into the following issue. I'm hesitant to file this issue given how quickly things are changing on io.js and the fact that it is currently considered an 'alpha, but putting it on your radar here.

io.js recently (*see* [io.js/commit/0bf1d124](https://github.com/iojs/io.js/commit/0bf1d124af481ac9be095fcb846a1aad08595233#diff-1334479bba4bea496229d9e955ed2c58)) updated the C++ bindings for the HTTP parser, changing the signature for `onHeadersComplete` from:

    function onHeaderComplete(info)

to:

    function onHeadersComplete(versionMajor, versionMinor, headers, method, url,
                               statusCode, statusMessage, upgrade, shouldKeepAlive)

The current reliance on `process.binding('http_parser').HTTPParser` is very convenient, but may lead to some hacking to support different versions of Node.js / io.js where the C++ bindings change.

Happy to help work on solutions to this issue pending your thinking on the subject.

---

A work-around, for users looking to get this package working on io.js as of v1.0.3, can apply the following diff:

```diff
diff --git a/lib/websocket/http_parser.js b/lib/websocket/http_parser.js
index f8cda90..e0420af 100644
--- a/lib/websocket/http_parser.js
+++ b/lib/websocket/http_parser.js
@@ -29,12 +29,14 @@ var HttpParser = function(type) {
       self.headers[current] = value;
   };
 
-  this._parser.onHeadersComplete = this._parser[HTTPParser.kOnHeadersComplete] = function(info) {
-    self.method     = (typeof info.method === 'number') ? HttpParser.METHODS[info.method] : info.method;
-    self.statusCode = info.statusCode;
-    self.url        = info.url;
+  this._parser.onHeadersComplete = this._parser[HTTPParser.kOnHeadersComplete] = function(versionMajor, versionMinor,
+                                   headers, method, url, statusCode, statusMessage, upgrade, shouldKeepAlive) {
 
-    var headers = info.headers, key, value;
+    self.method     = (typeof method === 'number') ? HttpParser.METHODS[method] : method;
+    self.statusCode = statusCode;
+    self.url        = url;
+
+    var headers = headers, key, value;
     if (!headers) return;
 
     for (var i = 0, n = headers.length; i < n; i += 2) {
```

cc: iojs/io.js#456 / @jdimond

**Comment by jcoglan** [comment]
This should be fixed in bdc081a, and should be backward-compatible with older stable Node releases.

**Comment by robertdimarco** [comment]
@jcoglan Thank you! :+1:

**Comment by robertdimarco** [comment]
@jcoglan Also, for the update to the `faye-websocket-node` package and the multiple NPM version bumps, would you like me to send PRs?

**Comment by jcoglan** [comment]
I'm not sure what you mean about updating `faye-websocket-node` and version bumps. All that needs to be done is to release a new version of this module.

**Comment by robertdimarco** [comment]
@jcoglan Disregard my last comment, it looks like this will automatically be picked up by the faye-websocket-node package after the next release (per [package.json#L11](https://github.com/faye/faye-websocket-node/blob/master/package.json#L11)).

**Comment by robertdimarco** [comment]
@jcoglan I'm sorry for being a pest on this project, but could I trouble you for an NPM release of the latest update of this module? I'm pretty eager to make use of your latest changes. Appreciate the help.

**Comment by jcoglan** [comment]
Not yet, I'm still working on other issues that came up while I was taking some time off. The pre-release testing on this module takes a long time so I prefer to batch together as many fixes as I can rather than doing lots of small releases.

**Comment by robertdimarco** [comment]
That works, thanks for the follow-up :+1:
