### ISSUE TITLE
Connecting to remote websocket?

### ISSUE THREAD

**Issue by goette** [faye/websocket-driver-node#14]
Hey,

I am trying quite desperately to connect to an external websocket (that is not running on my server).

If my server is running on port 3000, I would like the client to connect to ```ws://localhost:3000``` and on the server proxy this request to the external websocket. I made a multitude of attempts to achieve this seemingly simple task, with the normal http-proxy module, but I always fail, because client and external websocket are obviously not on the same server, which makes the handshake problematic.

Is it possible to achieve this with websocket-driver? The upgrade event is fired, but the proxy never seems to connect:

```javascript
var http = require('http');
var net = require('net');
var websocket = require('websocket-driver');

var server = http.createServer(app);
server.on('upgrade', function(request, socket, body) {
    if (!websocket.isWebSocket(request)) return;

    var driver = websocket.client('ws://echo.websocket.org');
    var proxy  = driver.proxy('http://localhost:3000');
    var tcp = net.connect(3000, 'localhost');

    tcp.pipe(proxy).pipe(tcp, {end: false});

    tcp.on('connect', function() {
        proxy.start();
        console.log('started'); // This logs
    });

    proxy.on('connect', function() {
        console.log('connected'); // This doesn't log
        driver.io.pipe(tcp).pipe(driver.io);
        driver.start();
    });

    driver.messages.on('data', function(message) {
        console.log('Got a message', message);
    });
});
server.listen(process.env.PORT || 3000);
```

Thank you so much for any hints if this is possible using websocket-driver only!

**Comment by jcoglan** [comment]
I'm not sure I've understood what you're trying to do here. Is the above code the server that runs on `localhost:3000`, or is that a different server? Which endpoint does the end user connect to -- do they connect directly to `localhost:3000` without being aware that `echo.websocket.org` exists, or does it connect to `echo.websocket.org` but using `localhost:3000` as a proxy?

**Comment by goette** [comment]
Thanks for your quick reply.

The end user would connect to ```ws://localhost:3000``` without being aware that ```echo.websocket.org``` is the actual websocket server he is talking to.

The intention for doing this is just to protect the connection to the websocket server. Since it has no authentication handling itself, it's an additional layer of security to not expose its URL to the client / the end user.

If the websocket ran on a different port on the same server, i.e. ```localhost:8080```, it would be no problem to achieve that. The tricky part seems to be that the websocket server i want to connect to is on a different server (in this case websocket.org).

Is that possible to achieve? Thanks again for your help.

**Comment by gagern** [comment]
See also https://www.npmjs.com/package/http-proxy#proxying-websockets

**Comment by goette** [comment]
I tried ```http-proxy``` in a multitude of ways. As long as I'm proxying to a Websocket on the same server i.e. localhost:8080 to localhost:9090, all is working well. But the problem appears, when i want to proxy localhost:8080 to echo.websocket.org. Same problem as I described above: the cross-sever handshakes keep dying on me. That's why I wondered if websocket-driver would be able to do that instead?

**Comment by jcoglan** [comment]
Ah, it seems like you're using the `proxy()` function for something it's not intended to do. `proxy()` is used for making a *client* connect to some server (say `echo.websocket.org`) but do so via some other server that it needs to use as a proxy (say `proxy.example.com`). In this case, the client sends a `CONNECT` request to `proxy.example.com`, which then acts as a TCP proxy to `echo.websocket.org`, and the WebSocket handshake is then performed via this proxied connection.

It is *not* used to implement opaque proxying on the server side. To do that, it's probably simplest to use `faye-websocket`, for example:

```js
var http = require('http'),
    WebSocket = require('faye-websocket');

var server = http.createServer();

server.on('upgrade', function(request, socket, body) {
  var frontend = new WebSocket(request, socket, body),
      backend  = new WebSocket.Client('ws://echo.websocket.org' + request.url);

  frontend.pipe(backend).pipe(frontend);
});
```

That is, when the server receives a WebSocket connection, it opens its own WebSocket to `echo.websocket.org`, and pipes data between the two connections. If you just had a TCP proxy that forwarded the incoming data to `echo.websocket.org`, it will probably fail because the `Host` header on the incoming request won't match what the upstream server is expecting.

**Comment by jcoglan** [comment]
Of course, this might generate unnecessary overhead of parsing and encoding websocket frames, especially if either connection is using permessage-deflate. You could instead open a plain TCP connection to `echo.websocket.org` and perform your own WebSocket handshake on that connection, and then forward all the incoming TCP data from `socket` to this backend connection and vice versa.  I'm not sure `websocket-driver` provides any way to do this though; you can't get it to perform a handshake and then stop processing the actual framing protocol. I'll see if I can figure something out though.

**Comment by jcoglan** [comment]
Okay it turns out you can use websocket-driver just to perform the handshakes with the client and the backend server, and then transparently forward the TCP streams between the client and the backend. This seems to work, but might require a bit more work to iron out some edge cases:

```js
var driver = require('websocket-driver'),
    http = require('http'),

var proxy = http.createServer();
proxy.listen(3000);

proxy.on('upgrade', function(request, socket, body) {
  var frontend = driver.http(request);
  frontend.io.pipe(socket);

  var tcp = net.connect(80, 'echo.websocket.org'),
      backend = driver.client('ws://echo.websocket.org/');

  backend.io.pipe(tcp).pipe(backend.io);

  backend.on('open', function() {
    tcp.unpipe(backend.io);
    tcp.pipe(socket);
  });

  tcp.on('connect', function() {
    frontend.start();
    backend.start();
    socket.pipe(tcp);
  });
});
```

**Comment by goette** [comment]
Wow thank you so much for these very helpful and detailed responses! Your first example, using faye-websocket, is working like a charm for me. Especially, it works great with clusters as well, not a single failed handshake. I would love to use the second version rather, since it's less "blackbox-y". But as you said, there will be edge cases, the first being clustering as it seems, which I couldn't get to work without several fails. I would probably need to attach the connections to a session handler like redis to make them persistent, right?  I don't fully understand, why this is not necessary with the first version, but it seems just work, so great!
