### ISSUE TITLE
Can't browserify - process.binding is not supported

### ISSUE THREAD

**Issue by alanshaw** [faye/websocket-driver-node#15]
http_parser.js uses `process.binding` but this is not supported by browserify so I get a runtime error.
https://github.com/faye/websocket-driver-node/blob/master/lib/websocket/http_parser.js#L3

**Comment by jcoglan** [comment]
websocket-driver is not intended for use in the browser. Can you give me some more context about what you're trying to do?

**Comment by Terentich** [comment]
Hi! I have the same problem. My configuration below. Could you please tell me how you fix that?
app.js:
import 'angular';
import 'sockjs';
import 'stompjs';
import 'ng-stomp';

class MetaCtrl {
    constructor($stomp) {
        $stomp.setDebug(function (args) {
            console.log(args);
        });

        $stomp
            .connect('/api/job/updates')
            .then(function (frame) {
                var subscription = $stomp.subscribe('/api/job/updates', function (payload, headers, res) {
                    $scope.payload = payload;
                }, {
                    'headers': 'are awesome'
                });

                $stomp.disconnect(function () {
                    console.log('disconnected');
                });
            });
    }
}

angular.module('mass.meta', ['ngStomp'])
    .controller('MetaCtrl', MetaCtrl);

export {MetaCtrl};

package.json:
{
  "devDependencies": {
    "babel-preset-es2015": "latest",
    "babelify": "latest",
    "browser-sync": "^2.13.0",
    "browserify": "^13.0.1",
    "gulp": "^3.9.1",
    "gulp-clean-css": "latest",
    "gulp-concat-css": "latest",
    "gulp-sourcemaps": "latest",
    "gulp-uglify": "latest",
    "gulp-util": "latest",
    "http-proxy-middleware": "latest",
    "lodash": "latest",
    "rimraf": "latest",
    "vinyl-buffer": "latest",
    "vinyl-source-stream": "latest",
    "watchify": "latest"
  },
  "dependencies": {
    "angular": "^1.5.5",
    "angular-animate": "^1.5.5",
    "angular-aria": "^1.5.5",
    "angular-material": "^1.0.8",
    "angular-messages": "^1.5.5",
    "angular-mocks": "^1.5.5",
    "angular-moment": "^1.0.0-beta.6",
    "angular-route": "^1.5.5",
    "angular-sanitize": "^1.5.5",
    "bragi-browser": "0.0.12",
    "lf-ng-md-file-input": "^1.4.7",
    "moment": "^2.13.0",
    "ng-redux": "^3.0.0",
    "ng-stomp": "^0.2.0",
    "ngcomponentrouter": "^2.1.0",
    "redux": "^3.0.0",
    "redux-logger": "^2.6.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^1.0.2",
    "sockjs": "^0.3.17",
    "sockjs-client": "^1.1.1",
    "stompjs": "^2.3.3"
  }
}

**Comment by jcoglan** [comment]
@Terentich Using websocket-driver with Browserify is not supported. Modules depending on it should use the browser's `WebSocket` class instead.

**Comment by Terentich** [comment]
But I didn't use these classes, I'm just included libraries. 
Probably for me the problem appears than I try to use ES6 module loading.
I have changed the code.

Before:
`
import 'angular';
import 'sockjs';
import 'stompjs';
import 'ng-stomp';
`

After:
`
import 'ng-stomp/dist/ng-stomp.standalone.min';
`

And everything works fine.

**Comment by rriemann** [comment]
Please re-open. I use `import faye from 'faye/src/faye_browser';` to import faye with jspm/SystemJS and get the same error.

**Comment by jcoglan** [comment]
@rriemann what's the chain of files between `faye/src/faye_browser` and this module that causes it to be loaded? You should not need to require that file specifically; importing `faye` should work fine and as of 1.2.0 (released June 2016) this works with Browserify and Webpack.

I'm not familiar with SystemJS so it would be helpful to understand why it's trying to load modules that should only be used on the server.

**Comment by jcoglan** [comment]
(In the upcoming release of this package, the HTTP parser no longer relies on `process.binding` but instead uses `http-parser-js`, but that's incidental. The fundamental problem is that browser build tools should not be attempting to load this package.)

**Comment by jcoglan** [comment]
OK so I've done a little cursory investigation and got this error when trying to run `import faye from 'faye'`:

```
Uncaught (in promise) Error: (SystemJS) process.binding is not supported
	Error: process.binding is not supported
	    at Object.process.binding (http://localhost:8000/jspm_packages/npm/process@0.11.10/browser.js:177:11)
	    at eval (http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/http_parser.js:4:32)
	    at Object.eval (http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/http_parser.js:86:3)
	    at eval (http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/http_parser.js:88:4)
	    at eval (http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/http_parser.js:89:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/http_parser.js
	Evaluating http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/driver/client.js
	Evaluating http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5/lib/websocket/driver.js
	Evaluating http://localhost:8000/jspm_packages/npm/websocket-driver@0.6.5.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye-websocket@0.11.1/lib/faye/websocket.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye-websocket@0.11.1.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/util/websocket/node_websocket.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/transport/web_socket.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/transport/node_transports.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/protocol/dispatcher.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/protocol/client.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4/src/faye_browser.js
	Evaluating http://localhost:8000/jspm_packages/npm/faye@1.2.4.js
```

`src/transport/web_socket.js` is causing `src/util/websocket/node_websocket.js` to be loaded, which is wrong -- it should use `src/util/websocket/browser_websocket.js` and then nothing in the trace above that line will be loaded.

Do you know what I should do to make SystemJS load `src/util/websocket/browser_websocket.js`, or is this a bug in SystemJS?

**Comment by jcoglan** [comment]
I also notice that in `config.js`, jspm is mapping a lot of modules for Faye that it should be ignoring since they're not used in the browser client: `buffer`, `crypto`, `csprng`, `faye-websocket`, `fs`, `http`, `https`, `path`, `process`, `querystring`, `tough-cookie`, `tunnel-agent` and `url`. The client does not depend on any Node modules and jspm should not be mapping those.

However it looks as though [they don't plan to support the `browser` field in `package.json`](https://github.com/systemjs/systemjs/issues/860), in which case I'm not sure what to suggest.

**Comment by rriemann** [comment]
I prepared a minimal example for testing: https://github.com/rriemann/faye-systemjs-issue

I think it would be possible to import faye on the server with:

```js
import faye from `faye`
// or
import faye from `faye/server`
```

and use the following to get the client file:

```js
import faye from `faye/client`
```

Therefore, one needs to have files index.js, server.js and client.js that have the correct imports. However, I am not a JSPM nor systemjs, nor js expert. 😬

**Comment by jcoglan** [comment]
@rriemann Faye already contains an entry point specifically for the browser: https://github.com/faye/faye/blob/1.2.4/src/faye_browser.js. The problem is that JSPM is not loading that, because it ignores the [`browser` field in `package.json`](https://github.com/faye/faye/blob/1.2.4/package.json#L11).

But, even if you import `faye_browser.js` explicitly, it still won't work because Faye uses `package.json` in its internal structure, because multiple internal components have different versions for Node and the browser. For example these modules: [`browser`](https://github.com/faye/faye/blob/1.2.4/src/util/browser/package.json), [`cookies`](https://github.com/faye/faye/blob/1.2.4/src/util/cookies/package.json), [`websocket`](https://github.com/faye/faye/blob/1.2.4/src/util/websocket/package.json) and [`transport`](https://github.com/faye/faye/blob/1.2.4/src/transport/package.json). A build tool needs to use these files to determine the right version of each module to load, and Browserify and Webpack both do this. From JSPM's issue history it looks like they've decided not to support this.
