### ISSUE TITLE
`this._frame` is undefined

### ISSUE THREAD

**Issue by fpereira1** [faye/websocket-driver-node#18]
Hi,

I encountered an error in production that is hard to reproduce, we depend on this module because it's being used by firebase 2.x on npm.

The error happens on this line https://github.com/faye/websocket-driver-node/blob/0.5.4/lib/websocket/driver/hybi.js#L142 where `this._frame` is undefined, which causes our node application to crash.

It only started happening after we migrated our application to node 4, on node 0.10 we didn’t have this issue.

When we added some logging if `this._frames`is undefined we got something interesting.  we added `console.log(data);` and the result is that `data` looks to be broken (starting with `true`)

```
UNDEFINED FRAME LENGTH �~;
UNDEFINED FRAME LENGTH true,\"path\":\"/\"}
```

Is this a known issue or are you able to hlep resolve?

Thanks!

**Comment by jcoglan** [comment]
Before I dig into this, have you tried upgrading to the latest release? Also, where exactly did you put this `console.log(data)` call?

**Comment by fpereira1** [comment]
Hey,

I haven't yet tried to upgrade to the latest version because the firebase 2.x npm module was still using 0.5.2 (through npm shrinkwrap) [firebase@2.4.2/npm-shrinkwrap.json](https://npmcdn.com/firebase@2.4.2/npm-shrinkwrap.json), so we upgraded to 0.5.4, but thought 0.6 was a bigger jump, but since 0.5.4 didn't solve the problem, we might upgrade to 0.6.

I added the console.log on [line 142](https://github.com/faye/websocket-driver-node/blob/0.5.4/lib/websocket/driver/hybi.js#L142)

so it looked like this:

```
     case 4:
          if(!this._frame) {
              console.log(data);
          }
          buffer = this._reader.read(this._frame.length);
          if (buffer) {
            this._emitFrame(buffer);
            this._stage = 0;
          }
          break;

```

**Comment by jcoglan** [comment]
You should probably try upgrading first before we investigate further. I've had other bug reports from Firebase users running old websocket modules.

**Comment by jcoglan** [comment]
Did you ever find out if upgrading solved the problem?

**Comment by fpereira1** [comment]
@jcoglan upgrading to 0.6 didn't fix the issue, then we decided to upgrade from Firebase 2.x to 3 and we haven't had that issue since.  Feel free to close it, thanks for your help! 👍
