### ISSUE TITLE
Question - how to obtain the IP address of the client

### ISSUE THREAD

**Issue by ikb42** [faye/websocket-driver-node#20]
Hi
How could I obtain the IP address of a connected client?
Sorry, I know this is not an issue.
Thanks

**Comment by jcoglan** [comment]
This module doesn't provide this functionality. It only deals with the *data* that flows over the connection, not the connection itself. To get the IP address, you need to ask the TCP or TLS socket object that you're piping into this module.

Does that make sense?

**Comment by jcoglan** [comment]
Can I close this issue, or did you have further questions?

**Comment by ikb42** [comment]
Thanks, I have a further question, could I detect when the TCP layer is still busy sending a message - eg so that I can not expect ping responses?

**Comment by jcoglan** [comment]
Again, that's the concern of the network streams that you connect this module to, not this module itself.

It does implement the Node back-pressure mechanism so for example if `messages.write()` returns `false` that's an advisory signal that it's getting backed up writing messages out to TCP and you should back off.

**Comment by ikb42** [comment]
Thanks very much.
