### ISSUE TITLE
Change to websocket-driver-node broke build

### ISSUE THREAD

**Issue by slatron** [faye/websocket-driver-node#22]
I am using gulp-connect which has this as a downstream package dependency.

Today, it seems that our build broke based on a new dependency call to http-replace-js from this repository. Pervious builds that succeeded did not include "http-replace-js", which seems to have been added by this module (websocket-driver-node)

Dependency chain is gulp-connect > tiny-lr > faye-websocket > websocket-driver

The error is reported as "Error: Cannot find module 'http-parser-js'"

Has anyone else been seeing / reporting this error? It is breaking our entire application.

**Comment by jcoglan** [comment]
I'm not sure what `http-replace-js` is but `http-parser-js` refers to [this package](https://www.npmjs.com/package/http-parser-js), which should be installed when you run `npm install` for this package.

**Comment by slatron** [comment]
@jcoglan - Yes, I meant `http-parser-js` - sorry for the typo.

The problem persists - but I noticed that you appear to have an old version of `http_parser.js` in your lib folder of this project.

When I manually replace that file with the current version of `http_parser.js` from their repo, the problem is fixed:

https://github.com/creationix/http-parser-js/blob/master/http-parser.js

Notice the difference between that file and the one currently in your lib folder:

https://github.com/faye/websocket-driver-node/blob/master/lib/websocket/http_parser.js

Please advise if there is anything I can do to fix. Thank you!

**Comment by jcoglan** [comment]
The `http_parser.js` file in this repository is a wrapper around, originally the Node.js HTTP parser, and now `http-parser-js`. Replacing it with the file you mentioned changes the interface it exports and therefore breaks the client driver.

Are you able to determine why replacing that file fixes your build problem? Is it related to which `require()` calls are being made, or entry points defined in `package.json` files? (I don't know how you build process resolves dependencies.)

**Comment by slatron** [comment]
Thanks, we're looking into it from here to see why we don't get the `http-parser-js` original file. It looks like node sees your updated wrapper for `http-parser.js` and does not import the original `http-parser.js` file.

Thanks for your assistance in finding this issue. I'll see what we can do with our build process.

**Comment by slatron** [comment]
I had to force  v0.6.5 of websocket-driver to get the application to build again from missing `http-parser-js`.

Only other issue I noticed is the monkeypatch warning in their readme file:
https://github.com/creationix/http-parser-js/blob/master/README.md

Is is possible this needs to be added to your version?

```
// Monkey patch before you require http for the first time.
process.binding('http_parser').HTTPParser = require('http-parser-js').HTTPParser;

var http = require('http');
// ...
```

**Comment by jcoglan** [comment]
> Is is possible this needs to be added to your version?

No; that would replace the HTTP parser for the entire Node process, which is not what we want.
