### ISSUE TITLE
Null pointer error when process.version is empty string

### ISSUE THREAD

**Issue by xsigik** [faye/websocket-driver-node#26]
I got null pointer error, because process.version returns empty string, so match() returns null and map() falls. Version of websocket-driver 0.7.0. Version of nodejs v8.9.1.
`var VERSION = process.version.match(/[0-9]+/g).map(function(n) { return parseInt(n, 10) });`

**Comment by jcoglan** [comment]
Can you find out why `process.version` is an empty string on your Node installation?

**Comment by dcarabott** [comment]
@xsigik Have you figured this one out? I'm having the same issues when using angular-cli.

**Comment by xsigik** [comment]
@dcarabott Hi, I figured it out by using newer version of Node :) No time for debugging Node, but it happened only in some version of Node.

**Comment by dcarabott** [comment]
@xsigik Damn! I'm on v6.9.4. Which version works for you? Thanks!!

**Comment by xsigik** [comment]
I have 9.2.0 but I think both LTS (8.9.4) and current (9.5.0) are ok...

**Comment by dcarabott** [comment]
Guess my problem is a little bit more difficult than that. Updated node but still having issues.

**Comment by jcoglan** [comment]
This should be fixed in commit 5723676 -- can you confirm for me?

**Comment by GIn-Liu** [comment]
现在process依旧会出现''.map的情况，报typeError的错误
