### ISSUE TITLE
Incorrect handling sec-headers at draft76.js of this protocol realization

### ISSUE THREAD

**Issue by novoden80** [faye/websocket-driver-node#27]
The problem has at file websocket-driver-node/blob/master/lib/websocket/driver/draft76.js
The following functions, that uses RegExp match are wrong:
```
var numberFromKey = function(key) {
  return parseInt(key.match(/[0-9]/g).join(''), 10);
};

var spacesInKey = function(key) {
  return key.match(/ /g).length;
};
```
When characters at parameter key does not match regexp pattern, then match() function will return null, and we will have and Unhandled Exception Error. This functions using to handle ``sec-websocket-key1`` and ``sec-websocket-key2`` headers, so incorrect handshake over draft76 protocol will crash any service, with faye/websocket-driver-node, for example:
```
curl -v -H 'upgrade: websocket' -H 'connection: upgrade' -H 'sec-websocket-key1: 12998 5 Y3 1 .P00' -H 'sec-websocket-key2: abs @ew dsdsxWdd d s' -H 'websocket-protocol: sample' "http://127.0.0.1:3000/tstwebsock"
```

**Comment by jcoglan** [comment]
Thanks for reporting this. Can you check if #28 fixes this problem?

**Comment by novoden80** [comment]
Thank you. I've checked PR#28 some days ago. It's fixes this problem.

**Comment by jcoglan** [comment]
This bug can no longer be reproduced as of https://github.com/faye/websocket-driver-node/commit/287bbe8a7a9b52fa19f0135641573892c6750088, which fixes the problem more generally by wrapping all handshake response generation in an error handler.
