### ISSUE TITLE
Event on data flush when sending.

### ISSUE THREAD

**Issue by koper89** [faye/websocket-driver-node#32]
Is there a way to get some confirmation of actual stream write finish, or in example attach a callback on flush of data in streams? As currently I'm experiencing problem that when i send packet that takes long time, let's say 50 seconds, which is longer than my ping rate, in this scenario I'll not be able to detect that my ping was not delivered/responded in time because I'm still transmitting the message.

**Comment by jcoglan** [comment]
I don't think there's any way for this library to report on that. It doesn't perform any buffering itself, it just emits `data` events that are passed via `pipe()` into whatever I/O stream you've connected it to. It's possible that that `net` or `tls` stream can provide information about how much data is in its write buffer?

**Comment by jcoglan** [comment]
Did this answer your question, @koper89? Can I close this issue?

**Comment by koper89** [comment]
Yep, thanks for help!
