### ISSUE TITLE
driver.on('pong', callback) not being called

### ISSUE THREAD

**Issue by ikb42** [faye/websocket-driver-node#36]
Hi
version 0.7.3
My callback is not being called when used via the event emitter:

`driver.on('pong', callback)`

When using a callback on the ping function itself it does get called:
`driver.ping(x, callback)`

Thanks

**Comment by jcoglan** [comment]
I believe this is fixed in d892d3bad5eeedcf84b112200f4b806e3aaace93 -- can you check?

**Comment by jcoglan** [comment]
This problem has been fixed in version `0.7.4` so I'm closing this issue.
