### ISSUE TITLE
enumerable property causes server to abort

### ISSUE THREAD

**Issue by dceejay** [faye/websocket-driver-node#42]
On a chrome based client connecting to a nodejs sever I've started to get the following error - which causes the entire server to abort and crash.
```
LOG info GET /myapp/socket/info?t=1635790354878 3ms 200
LOG error Exception on "GET /myapp/socket/776/vp3on54j/websocket" in filter "sockjs_websocket":
Error: Unrecognized option: getKey
    at Function.Base.validateOptions (/Users/conway/Projects/myapp/node_modules/websocket-driver/lib/websocket/driver/base.js:41:13)
    at Hybi.Base (/Users/conway/Projects/myapp/node_modules/websocket-driver/lib/websocket/driver/base.js:12:8)
    at new Hybi (/Users/conway/Projects/myapp/node_modules/websocket-driver/lib/websocket/driver/hybi.js:12:8)
    at Function.Server.http (/Users/conway/Projects/myapp/node_modules/websocket-driver/lib/websocket/driver/server.js:105:12)
    at Object.http (/Users/conway/Projects/myapp/node_modules/websocket-driver/lib/websocket/driver.js:27:24)
    at new WebSocket (/Users/conway/Projects/myapp/node_modules/faye-websocket/lib/faye/websocket.js:17:25)
    at App.sockjs_websocket (/Users/conway/Projects/myapp/node_modules/sockjs/lib/trans-websocket.js:25:12)
    at execute_request (/Users/conway/Projects/myapp/node_modules/sockjs/lib/webjs.js:22:37)
    at IncomingMessage.req.next_filter (/Users/conway/Projects/myapp/node_modules/sockjs/lib/webjs.js:100:18)
    at Listener.webjs_handler (/Users/conway/Projects/myapp/node_modules/sockjs/lib/webjs.js:102:13)
```
Looking at the code at that point (base.js line 41)
```
Base.validateOptions = function(options, validKeys) {
  for (var key in options) {
    if (validKeys.indexOf(key) < 0)
      throw new Error('Unrecognized option: ' + key);
  }
};
```
you can see it is not checking for only local properties and for some reason options seems to now have an enumerable property called getKey

The fix is the time honoured method of adding an if (options.hasOwnProperty(key)) { within the for loop to only check against valid properties.

Any chance this could get patched and released ?

Originally found while using sockjs and reported over there https://github.com/sockjs/sockjs-node/issues/294 which uses faye-websocket so that may need a bump also.

**Comment by jcoglan** [comment]
This looks like a duplicate of https://github.com/faye/websocket-driver-node/pull/41, which raises a couple of questions about the cause of the problem:

- The client should not have any influence over the options object passed to the server-side WebSocket handler
- The server should handle the fact that `websocket-driver` and `faye-websocket` constructors can throw errors without crashing

If the origin of the `getKey` property is part of your program or part of SockJS, then my usual advice would be to remove it from the options object or make it non-enumerable. If you have no control over the fact that `getKey` is being added to the options object then we should find out how it's being added and then see where to go from there.

**Comment by dceejay** [comment]
conversely - why not program defensively as it's a well known problem ?... with a well know solution.
https://www.javascripttutorial.net/javascript-for-in/
https://stackoverflow.com/questions/684672/how-do-i-loop-through-or-enumerate-a-javascript-object
https://stackoverflow.com/questions/32422867/when-do-i-need-to-use-hasownproperty/32422910
etc, etc

I will try to track down where the prototype is being modified but it could be in any dependency, - and I'm not sure how to remove it if added - a simple delete won't touch it.

**Comment by jcoglan** [comment]
I am aware of how properties are iterated and how to exclude inherited properties if that's what you want. In this case I have _intentionally_ decided not to exclude them. The presence of unrecognised properties in options objects usually indicates a program error and it also makes it harder to add new options in future without breaking existing programs. Restricting the keys that callers can pass in options objects means we can be sure that any option we add in future will not be being used by any existing program and is therefore a backwards-compatible addition.

In the case of the linked PR, the addition of the extra property was happening in the author's own source code so they could make it non-enumerable. If the addition of this `getKey` property is not under your control, my preferred solutions would be either:

- the package that is adding `getKey` marks it non-enumerable
- the package passing options into `faye-websocket` and `websocket-driver` uses `Object.create(null)` to avoid inheriting unwanted keys in the options object

**Comment by dceejay** [comment]
OK - will look elsewhere for a fix
